apiVersion: v1
kind: Service
metadata:
    name: "l3monitfk8s-8ddc"
    labels:
        app: "l3monitfk8s-8ddc"
spec:
    type: LoadBalancer
    ports:
    - port: 7777
      targetPort: 7777
      protocol: TCP
      name: http
    selector:
        app: "l3monitfk8s-8ddc"