on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: l3moni.azurecr.io
        username: ${{ secrets.acr_l3moni_username }}
        password: ${{ secrets.acr_l3moni_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/containers/vanilla/1.4.3.2" -f  "containers/vanilla/1.4.3.2/Dockerfile" -t l3moni.azurecr.io/l3monitfk8s:${{ github.sha }} --label dockerfile-path=containers/vanilla/1.4.3.2/Dockerfile
        docker push l3moni.azurecr.io/l3monitfk8s:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_l3monitfk8s_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep efi-servers | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace efi-servers`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: efi-servers
        container-registry-url: l3moni.azurecr.io
        container-registry-username: ${{ secrets.acr_l3moni_username }}
        container-registry-password: ${{ secrets.acr_l3moni_password }}
        secret-name: l3monitfk8sdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: efi-servers
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          l3moni.azurecr.io/l3monitfk8s:${{ github.sha }}
        imagepullsecrets: |
          l3monitfk8sdockerauth
